language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - node_modules

jdk:
  - oraclejdk11
  - openjdk11

before_install:
  - docker-compose up -d

after_script:
  - docker-compose down
