version: '2.3'

services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=testmate
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  database-data:
