version: '2.3'

services:
  database-base:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=cozzer
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    extends:
      service: database-base
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  database-testing:
    extends:
      service: database-base
    # This is using a different image because Flyway doesn't support cleaning PostgreSQL 11 yet: https://github.com/flyway/flyway/issues/2178
    image: postgres:10-alpine
    ports:
      - "5434:5432"

volumes:
  database-data:
